import { ProductType } from "@/app/types/product";

export const products: ProductType[] = [
  {
    id: 1,
    name: "Bishop Cap Cactus",
    price: 3.99,
    images: [{ id: 1, url: "feather_cactus.jpeg" }],
    description: "Clear air and reduce stress.",
    sizes: [
      { label: "S", total: 10, sold: 5, inStock: 5 },
      { label: "M", total: 15, sold: 5, inStock: 10 },
      { label: "L", total: 8, sold: 8, inStock: 0 },
      { label: "XL", total: 5, sold: 3, inStock: 2 },
    ],
    onSale: true,
    discountPercentage: 20,
    size: "L",
    quantity: 17,
    sold: 5,
    rating: 4,
    review: 200,
    colors: [],
    availableColors: [],
    limitedColors: [],
    discount: 10,
    category: "bottle",
    favorite: false,
    createdAt: new Date(),
  },
  {
    id: 2,
    name: "Blue Columnar Cactus",
    price: 3.99,
    images: [{ id: 2, url: "plant-1.png" }],
    description: "Good for beginners and easy to care for.",
    sizes: [
      { label: "S", total: 5, sold: 0, inStock: 5 },
      { label: "M", total: 8, sold: 5, inStock: 3 },
      { label: "L", total: 6, sold: 2, inStock: 4 },
      { label: "XL", total: 2, sold: 1, inStock: 1 },
    ],
    onSale: false,
    discountPercentage: 0,
    size: "M",
    quantity: 8,
    sold: 5,
    rating: 4,
    review: 200,
    colors: [],
    availableColors: [],
    limitedColors: [],
    discount: 10,
    category: "bottle",
    favorite: false,
    createdAt: new Date(),
  },
  {
    id: 3,
    name: "Bunny Ears Cactus",
    price: 3.99,
    images: [{ id: 3, url: "plant-2.avif" }],
    description: "Cute and unique addition to any collection.",
    sizes: [
      { label: "S", total: 4, sold: 2, inStock: 2 },
      { label: "M", total: 6, sold: 6, inStock: 0 },
      { label: "L", total: 8, sold: 3, inStock: 5 },
      { label: "XL", total: 3, sold: 3, inStock: 0 },
    ],
    onSale: true,
    discountPercentage: 10,
    size: "M",
    quantity: 7,
    sold: 5,
    rating: 4,
    review: 200,
    colors: [],
    availableColors: [],
    limitedColors: [],
    discount: 10,
    category: "bottle",
    favorite: false,
    createdAt: new Date(),
  },
  {
    id: 4,
    name: "Christmas Cactus",
    price: 3.99,
    images: [{ id: 4, url: "plant-3.png" }],
    description: "Perfect for holiday decor.",
    sizes: [
      { label: "S", total: 3, sold: 2, inStock: 1 },
      { label: "M", total: 4, sold: 2, inStock: 2 },
      { label: "L", total: 5, sold: 5, inStock: 0 },
      { label: "XL", total: 2, sold: 2, inStock: 0 },
    ],
    onSale: false,
    discountPercentage: 0,
    size: "M",
    quantity: 3,
    sold: 5,
    rating: 4,
    review: 200,
    colors: [],
    availableColors: [],
    limitedColors: [],
    discount: 10,
    category: "bottle",
    favorite: false,
    createdAt: new Date(),
  },
  {
    id: 5,
    name: "Fairy Castle Cactus",
    price: 3.99,
    images: [{ id: 5, url: "old_lady_cactus.jpeg" }],
    description: "Easy to care for and visually appealing.",
    sizes: [
      { label: "S", total: 3, sold: 2, inStock: 1 },
      { label: "M", total: 4, sold: 2, inStock: 2 },
      { label: "L", total: 5, sold: 5, inStock: 0 },
      { label: "XL", total: 2, sold: 2, inStock: 0 },
    ],
    onSale: false,
    discountPercentage: 0,
    size: "M",
    quantity: 3,
    sold: 5,
    rating: 4,
    review: 200,
    colors: [],
    availableColors: [],
    limitedColors: [],
    discount: 10,
    category: "bottle",
    favorite: false,
    createdAt: new Date(),
  },
  {
    id: 6,
    name: "Moon Cactus",
    price: 3.99,
    images: [{ id: 6, url: "moon_cactus.jpeg" }],
    description: "Gives a pop of color to any space.",
    sizes: [
      { label: "S", total: 3, sold: 2, inStock: 1 },
      { label: "M", total: 4, sold: 2, inStock: 2 },
      { label: "L", total: 5, sold: 5, inStock: 0 },
      { label: "XL", total: 2, sold: 2, inStock: 0 },
    ],
    onSale: false,
    discountPercentage: 0,
    size: "M",
    quantity: 3,
    sold: 5,
    rating: 4,
    review: 200,
    colors: [],
    availableColors: [],
    limitedColors: [],
    discount: 10,
    category: "bottle",
    favorite: false,
    createdAt: new Date(),
  },
];
